"""v1.0 plant and timing contract."""
TELEMETRY_GEA_CYCLE_MS = 730
TELEMETRY_ISHIDA_PROGRAM = "002"
BRINE_VOLUME_L = 700.0
BRINE_MANUFACTURER = "Bunge"
FEED_STREAM_NOMINAL_LPM = 12.5
TICK_MS = 10
SYNC_TOLERANCE_MS = 35
LAYER_COUNT = 14
